# Generated by Django 3.0 on 2019-12-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=20, verbose_name='Марка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='marka_logo/')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='ModelAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('body_type', models.CharField(max_length=20, verbose_name='Тип кузова')),
                ('power', models.IntegerField(default=0, verbose_name='Мощность,л.с.')),
                ('engine_volume', models.IntegerField(default=0, verbose_name='Объём двигателя,куб. см')),
                ('number_of_gears', models.IntegerField(default=0, verbose_name='Количество передач')),
                ('year_of_issue', models.IntegerField(default=0, verbose_name='Год выпуска')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('logo', models.ImageField(upload_to='model_logo/')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoHomeApp.Marka')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['model'],
            },
        ),
    ]
