# Generated by Django 3.0.3 on 2021-04-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdrive',
            options={'ordering': ['user'], 'verbose_name_plural': 'Тест-драйв'},
        ),
    ]
