# Generated by Django 3.0 on 2019-12-16 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoHomeApp', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Данные пользователей'},
        ),
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('body_type', models.CharField(max_length=20, verbose_name='Тип кузова')),
                ('power', models.IntegerField(default=0, verbose_name='Мощность,л.с.')),
                ('engine_volume', models.IntegerField(default=0, verbose_name='Объём двигателя,куб. см')),
                ('number_of_gears', models.IntegerField(default=0, verbose_name='Количество передач')),
                ('year_of_issue', models.IntegerField(default=0, verbose_name='Год выпуска')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('logo', models.ImageField(upload_to='model_logo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rezerv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Забронированные',
                'ordering': ['user'],
            },
        ),
    ]
