# Generated by Django 3.0 on 2019-12-17 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoHomeApp', '0003_auto_20191216_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerv', to=settings.AUTH_USER_MODEL),
        ),
    ]
